# Generated by Django 3.1.4 on 2021-01-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=1.8326094525995565e-05),
            preserve_default=False,
        ),
    ]
