# Generated by Django 3.1.4 on 2021-01-27 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_item_create_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='create_at',
        ),
    ]
