# Generated by Django 3.1.4 on 2021-01-27 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_comment_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='profile',
        ),
    ]
